name: tradologie_app
description: "A new tradologie flutter project."
publish_to: 'none'

version: 1.1.3+14

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  #! Core
  flutter_localization: ^0.3.2
  shared_preferences: ^2.2.3
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.0
  collection: ^1.18.0
  intl: ^0.20.2

  #! Image
  image_picker: ^1.1.2

  #! Network
  internet_connection_checker: ^3.0.1
  dio: ^5.5.0+1

  #! State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^9.2.0
  dartz: ^0.10.1

 

  #! Notifications
  flutter_local_notifications: ^20.0.0  
  firebase_messaging: ^16.1.1
  firebase_core: ^4.4.0
  
  #! View
  flutter_keyboard_visibility: ^6.0.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1
  pull_to_refresh: ^2.0.0
  fluttertoast: ^9.0.0
  pinput: ^6.0.1
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.11
  webview_flutter_wkwebview: ^3.23.5
  shimmer: ^3.0.0
  device_info_plus: ^12.3.0
  flutter_secure_storage: ^10.0.0
  country_picker: ^2.0.27
  dropdown_search: ^6.0.2
  share_plus: ^12.0.1
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.14.4


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
  
  #! Images
  - assets/images/
  - assets/images/2.0x/
  - assets/images/3.0x/
 

  fonts:
  - family: GeneralSans
    fonts:
    - asset: assets/fonts/GeneralSans-Bold.ttf
      weight: 900
    - asset: assets/fonts/GeneralSans-Semibold.ttf
      weight: 700
    - asset: assets/fonts/GeneralSans-Medium.ttf
      weight: 500
    - asset: assets/fonts/GeneralSans-Regular.ttf
      weight: 400
    - asset: assets/fonts/GeneralSans-Light.ttf
      weight: 300
    - asset: assets/fonts/GeneralSans-ExtraLight.ttf
      weight: 200
